### ISSUE TITLE
purpose of testing the mock GetPendingTasks method

### ISSUE THREAD

**Issue by xuefeng-huang** [nulab/go-todo-example#1]
Hi, @scarrupt 
Thanks for writing this tutorial on testing. I have leaned a lot.
But this is on thing I need some clarification, it bothers me a bit that in the following code:

https://github.com/nulab/go-todo-example/blob/415168bf3945a495650390c95cf98d0c7816377e/server/server_test.go#L26-L28

It made no sense to me to test the GetPendingTasks method on the mockedStore struct. That will be always a test pass, right? We are not testing the real GetPendingTasks method which iterate the tasks slice in Datastore struct, what is your thought?

**Comment by scarrupt** [comment]
Hi @xuefeng-huang ,

You are right, the mocked store always return the same value: 
https://github.com/nulab/go-todo-example/blob/415168bf3945a495650390c95cf98d0c7816377e/server/server_test.go#L156-L161
However, I want to check only the logic of the GetPendingTasks server function. A unit test should isolate the function that is tested from its dependencies, in this case, the store. The GetPendingTasks store function is already tested in store_test.go. 

Now, I could create an integration test to check the full logic including the retrieval of the data. 

This a simple application but in a more complex application, you should isolate your tests so you can easily know where the error is. If the store function fails and the server function doesn't. You know there is a problem with your store function but the server function logic is correct.

**Comment by xuefeng-huang** [comment]
Hi, @scarrupt 
Thanks for your answer and time, that definitely cleared my doubt.
